export const moods = [
    { label: "🤖 In the Zone", value: "in-the-zone" },
    { label: "🐞 Bugged Out", value: "bugged-out" },
    { label: "🔍 Code Detective", value: "code-detective" },
    { label: "🧠 Deep Focus", value: "deep-focus" },
    { label: "💡 Eureka Moment", value: "eureka-moment" },
    { label: "🧰 Fix-It Mode", value: "fix-it-mode" },
    { label: "💤 Burned Out", value: "burned-out" },
    { label: "🚀 Ready to Ship", value: "ready-to-ship" },
    { label: "🔄 Refactoring Spiral", value: "refactoring-spiral" },
    { label: "🔧 Tinkering", value: "tinkering" },
    { label: "🧩 Problem-Solving", value: "problem-solving" },
    { label: "⏳ Waiting on Build", value: "waiting-on-build" },
    { label: "🥱 Procrastinating", value: "procrastinating" },
    { label: "🌙 Night Owl", value: "night-owl" },
    { label: "🤯 Stuck in a Loop", value: "stuck-in-a-loop" },
    { label: "🎨 Creative Flow", value: "creative-flow" },
    { label: "🏃 Racing the Deadline", value: "racing-the-deadline" },
    { label: "🌐 Deep Dive", value: "deep-dive" },
];